#!/usr/bin/env python3
"""Generate a stub R.java from the app's real resources.

The Gradle build produces R.jar during processDebugResources; this sandbox cannot
run Gradle, and the cached R.jar predates newly added strings. Parsing the
resource files directly keeps the manual typecheck self-contained and honest:
every R.<type>.<name> referenced by the code either exists here or the compile
fails, so a missing/typo'd resource name is still caught.

Usage: python3 tools/gen_r_class.py <res-dir> <out-java-file> [package]
"""
import os
import re
import sys


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    res_dir, out_file = sys.argv[1], sys.argv[2]
    package = sys.argv[3] if len(sys.argv) > 3 else "org.nigao.zhihuLite"

    # res type -> resource names
    resources: dict[str, set[str]] = {}

    # Values files: values/, values-cn/, values-night/ ... all define the same names.
    for root, _dirs, files in os.walk(res_dir):
        base = os.path.basename(root)
        for fname in files:
            path = os.path.join(root, fname)
            if fname.endswith(".xml") and base.startswith("values"):
                with open(path, encoding="utf-8") as fh:
                    content = fh.read()
                # Top-level <string|color|dimen|bool|integer|style|array name="...">
                for m in re.finditer(r"<(\w+)[^>]*?\bname=\"([^\"]+)\"", content):
                    rtype, name = m.group(1), m.group(2)
                    # Skip nested declarations like <item name=...> inside a style/array.
                    if rtype == "item":
                        continue
                    resources.setdefault(rtype, set()).add(name)
            elif not fname.endswith(".xml"):
                # File-based resources: drawable/foo.png -> drawable.foo
                if base in ("drawable", "mipmap", "raw", "anim", "menu", "xml"):
                    stem = fname.rsplit(".", 1)[0]
                    # Skip density/qualifier variants already handled by the stem.
                    resources.setdefault(base, set()).add(stem)
                    # Also accept the un-suffixed name for e.g. ic_launcher_round.
                    resources.setdefault(base, set()).add(stem.split("_round")[0])

    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    lines = [
        "package %s;" % package,
        "",
        "// GENERATED by tools/gen_r_class.py from app/src/main/res. Do not commit.",
        "public final class R {",
    ]
    for rtype in sorted(resources):
        lines.append("    public static final class %s {" % rtype)
        for name in sorted(resources[rtype]):
            ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
            if not re.match(r"^[A-Za-z_]", ident):
                ident = "_" + ident
            lines.append("        public static final int %s = 0;" % ident)
        lines.append("    }")
    lines.append("}")
    with open(out_file, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    total = sum(len(v) for v in resources.values())
    print("R.java: %d resources across %d types -> %s" % (total, len(resources), out_file))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
